---

- name: Network Getting Started First Playbook
  connection: network_cli
  gather_facts: false
  hosts: switch
  tasks:

    - name: Get config for EXOS devices
      exos_facts:
        gather_subset: all

    - name: Display the config
      debug:
        msg: "The hostname iss {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"

    - name: configurable backup path
      exos_config:
        lines:
          - configure ports 2 description-string "Master Uplink"
        backup: yes
        backup_options:
          filename: backup.cfg
          dir_path: /root/git/muckaround